// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/verify" | "/dashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/verify.tsx": {
    id: "routes/verify";
    page: "/verify";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/verify": typeof import("./app/routes/verify.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
};